### ISSUE TITLE
__arch64__ in osdep.h should be __aarch64__

### ISSUE THREAD

**Issue by faultroll** [embedthis/appweb-gpl#3]
### Environment

1. O/S Version: debian 10.4.0

2. Appweb Version: 7.2.2

3. Hardware:

### Build

1. If built from source, what was your configure command line:

```
make "CC=aarch64-linux-gnu-gcc" "LD=aarch64-linux-gnu-ld" "AR=aarch64-linux-gnu-ar"
```
running the cross-compiler aarch64-linux-gnu

### Problem Description:

run ./appweb cause core-dump
gdb shows the crush at mprLib.c-->allocMem()-->acquire()
the qindex become a very large number (nagtive int), the findFirstBit(localMap) cannot get the proper "first-bit", for it recognize aarch64 as 32-bit not 64-bit that findFirstBit uses ffs not ffsl ( also ffsl is not good in 64-bit we should use ffsll instead, for long could be 32-bit in some cross-compiler)

**Comment by dev-embedthis** [comment]
ME_64 that controls 32 vs 64 bit. It should be set to 1.

It is set by:

#if __WORDSIZE == 64 || __amd64 || __x86_64 || __x86_64__ || _WIN64 || __mips64 ||    __arch64__ || __arm64__

in osdep/osdep.h

Can you check what symbol is defined by your aarch64 to indicate the architecture. It should have been __arch64__ or __arm64__.  Can you see what symbol is defined and we'll update osdep.h.

Thanks for reporting.

**Comment by dev-embedthis** [comment]
Is it:  

__aarch64__

**Comment by faultroll** [comment]
> 
> 
> Is it:
> 
> ```
> __aarch64__
> ```

yes

**Comment by dev-embedthis** [comment]
Thank you. We'll apply that to the next release.
