### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Gae-s** [embedthis/appweb-gpl#6]
### Issue Submission Template

Please follow this template when submitting each and every issue. Issues without these details will be marked as "Incomplete" and will not get attention. Make sure you use:

* Use markdown to format. Format code with three back ticks. Look at the source of this issue to see how it is done.

* Edit down any logs. Please do not just dump large unedited logs. Only post the relevant portions.

* Use the MakeMe **http** command in preference to a browser to trigger the issue. It is more controllable.

* Wherever possible, create an isolated test case, separate from your application to demonstrate the issue. This helps the team to recreate your issue.

* Include these details on ALL issues.

### Environment

1. O/S Version:Linux

2. Appweb Version:8.2.1

3. Hardware:

### Build

1. If built from source, what was your configure command line:make ARCH="arm" DEBUG="release" ME_COM_CGI=1

```
./configure [options] : none
```

### Problem Description:

Just compil with ME_COM_CGI option

> make ARCH="arm" DEBUG="release" ME_COM_CGI=1
>        [Run] make --no-print-directory -f projects/appweb-linux-default.mk all
>       [Info] Use make SHOW=1 to trace executed commands.
>    [Compile] build/linux-arm-default/obj/server.o
> src/http/server.c: In function ‘createEndpoints’:
> src/http/server.c:201:39: error: ‘SIGINFO’ undeclared (first use in this function); did you mean ‘SIGIO’?
>      app->signal = mprAddSignalHandler(SIGINFO, showState, 0, 0, MPR_SIGNAL_AFTER);
>                                        ^~~~~~~
>                                        SIGIO
> src/http/server.c:201:39: note: each undeclared identifier is reported only once for each function it appears in
> projects/appweb-linux-default.mk:549: recipe for target 'build/linux-arm-default/obj/server.o' failed
> make[1]: *** [build/linux-arm-default/obj/server.o] Error 1
> Makefile:45: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by mobsense** [comment]
This should fix it:

```
diff --git a/src/server.c b/src/server.c
index 216dd6ff..59cb0cb2 100644
--- a/src/server.c
+++ b/src/server.c
@@ -198,7 +198,7 @@ static int createEndpoints(int argc, char **argv)
         return MPR_ERR_CANT_CREATE;
     }
     mprGC(MPR_GC_FORCE | MPR_GC_COMPLETE);
-    app->signal = mprAddSignalHandler(SIGINFO, showState, 0, 0, MPR_SIGNAL_AFTER);
+    app->signal = mprAddSignalHandler(ME_SIGINFO, showState, 0, 0, MPR_SIGNAL_AFTER);
     return 0;
 }
```

and 

```
diff --git a/src/osdep/osdep.h b/src/osdep/osdep.h
index dd9b6e7a..1458f99a 100644
--- a/src/osdep/osdep.h
+++ b/src/osdep/osdep.h
@@ -1070,6 +1070,14 @@ typedef int64 Ticks;
     #define INADDR_NONE     ((in_addr_t) 0xffffffff)
 #endif

+#ifdef SIGINFO
+    #define ME_SIGINFO SIGINFO
+#elif defined(SIGIPRW)
+    #define ME_SIGINFO SIGIPRW
+#else
+    #define ME_SIGINFO NULL
+#endif
+
```

**Comment by Gae-s** [comment]
Sorry for my late answer.
Thank you, it is working fine
